export const texts = {
  OPERATION_SUCCESSFUL: "Operation successful",
  INVALID_NAME: "That is not a valid name",
  INVALID_ADDRESS: "This is not a valid address",
  INVALID_REQ_BODY: "Invalid request body",
  AN_ERROR_OCCURED: "An error occured. Please try again",
  METHOD_NOT_ALLOWED: "Method not allowed",
  NOT_FOUND: "Not found",
  VALIDATION_NOT_FOUND: "Validation not found",
  GATEWAY_NOT_FOUND: "Gateway not found",
  GATEWAY_CREATED: "Gateway created successfully",
  DEVICE_CREATED: "Device created successfully",
  GATEWAY_UPDATED:"Gateway updated successfully",
  GATEWAY_DELETED:"Gateway deleted successfully",
  DEVICE_DELETED:"Peripheral device deleted successfully",
  MASTERDEVICE_NOT_FOUND:"Master device not",
  ADDRESS_VERIFIED:"Address verified successfully",
  TOO_MANY_DEVICES:"Maximum of 10 devices allowed per gateway",
  SERIAL_NUMBER_REQUIRED:"Serial number is required",
  NAME_REQUIRED:"Name is required",
  IPADDRESS_REQUIRED:"IP address is required",
  IPADDRESS_INVALID:"IP address is invalid",
  UID_REQUIRED:"UID is required",
  VENDOR_REQUIRED:"Vendor is required",
  STATUS_REQUIRED:"Status is required",
  INVALID_STATUS:"Invalid status",
  DEVICE_NOT_FOUND:"Device not found",
  ADDRESS_NOT_VERIFIED:"Address not verified",
  INVALID_DATE:"Invalid date",
   }
